version: "2.0"
services:
  main:
    image: chandrastation/pkt_on_akash
    env:
      - WALLET_ADDR=your-address-here
      - POOLS="http://pool.srizbi.com http://pool.pktpool.io http://pool.pkt.world http://pool.pkteer.com"
    expose:
      - port: 3000
        as: 80
        to:
          - global: true

profiles:
  compute:
    miner:
      resources:
        cpu:
          units: 10
        memory:
          size: 1Gi
        storage:
          size: 1Gi
  placement:
    any:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        miner:
          denom: uakt
          amount: 1000

deployment:
  main:
    any:
      profile: miner
      count: 2
